// practices: [bdd-gherkin, llm-eval-harness]
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/boshu2/agentops/cli/internal/goals"
	"github.com/spf13/cobra"
)

var goalsRenderOut string

var goalsRenderCmd = &cobra.Command{
	Use:     "render",
	Short:   "Render GOALS.md directives and linked scenarios as BDD/Gherkin",
	GroupID: "analysis",
	Args:    cobra.NoArgs,
	Long: `Render the executable-spec layer as BDD/Gherkin text.

render is strictly READ-ONLY: it reads each GOALS.md directive's
"**Directive ID:**" and "**Scenarios:**" attributes plus the linked scenario
JSON files, and emits Gherkin. It never rewrites GOALS.md.

Each directive becomes a Gherkin "Feature" tagged with its stable directive ID
(@d-<id>). Each linked scenario becomes a "Scenario" tagged @<scenario-id>.
Gherkin steps come from the scenario's structured "given"/"when"/"then" arrays
when present; when a scenario lacks those, render emits a documented
best-effort step plus a comment noting the missing structured steps.

  ao goals render                 print Gherkin to stdout
  ao goals render --out spec.feature   write Gherkin to a file

Scenario content is resolved from spec/scenarios/<id>.json then
.agents/holdout/<id>.json (docs/adr/ADR-0003 resolution order).`,
	RunE: runGoalsRender,
}

// renderScenario is the subset of a scenario JSON document the renderer reads,
// including the optional structured given/when/then arrays (F1.1 schema
// additions) that goals render consumes to emit real Gherkin steps.
type renderScenario struct {
	ID    string   `json:"id"`
	Goal  string   `json:"goal"`
	Given []string `json:"given"`
	When  []string `json:"when"`
	Then  []string `json:"then"`
}

// runGoalsRender resolves GOALS.md, renders every directive and its linked
// scenarios to Gherkin, and writes the result to stdout or --out.
func runGoalsRender(cmd *cobra.Command, _ []string) error {
	patcher, _, err := goals.LoadGoalsPatcher(resolveGoalsFile())
	if err != nil {
		return fmt.Errorf("loading goals file: %w", err)
	}
	root := goalsRenderProjectRoot()
	gherkin := renderDirectivesGherkin(patcher.Directives(), root)
	if goalsRenderOut != "" {
		if err := os.WriteFile(goalsRenderOut, []byte(gherkin), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", goalsRenderOut, err)
		}
		fmt.Fprintf(cmd.OutOrStdout(), "Wrote Gherkin spec to %s\n", goalsRenderOut)
		return nil
	}
	fmt.Fprint(cmd.OutOrStdout(), gherkin)
	return nil
}

// goalsRenderProjectRoot returns the project root scenario files resolve
// against. The current working directory is the project root for CLI runs.
func goalsRenderProjectRoot() string {
	if wd, err := os.Getwd(); err == nil {
		return wd
	}
	return "."
}

// renderDirectivesGherkin renders every directive to a Gherkin Feature block,
// joined by blank lines, with a trailing newline.
func renderDirectivesGherkin(directives []goals.ParsedDirective, root string) string {
	var b strings.Builder
	b.WriteString("# Generated by `ao goals render` — do not edit. Source: GOALS.md\n")
	for i := range directives {
		b.WriteString("\n")
		renderDirectiveFeature(&b, directives[i], root)
	}
	return b.String()
}

// renderDirectiveFeature writes one directive as a tagged Gherkin Feature.
func renderDirectiveFeature(b *strings.Builder, d goals.ParsedDirective, root string) {
	id := d.StableID
	if id == "" {
		fmt.Fprintf(b, "# Directive #%d %q has no stable Directive ID; cannot tag a Feature\n", d.Number, d.Title)
		id = goals.SlugifyDirectiveID(d.Title)
	}
	fmt.Fprintf(b, "@%s\n", id)
	fmt.Fprintf(b, "Feature: %s\n", d.Title)
	if d.Steer != "" {
		fmt.Fprintf(b, "  # Steer: %s\n", d.Steer)
	}
	if d.Setpoint != "" {
		fmt.Fprintf(b, "  # Setpoint: %s\n", d.Setpoint)
	}
	if len(d.Scenarios) == 0 {
		b.WriteString("  # No scenarios linked to this directive.\n")
		return
	}
	for _, scenarioID := range d.Scenarios {
		b.WriteString("\n")
		renderScenarioBlock(b, scenarioID, root)
	}
}

// renderScenarioBlock writes one linked scenario as a tagged Gherkin Scenario.
func renderScenarioBlock(b *strings.Builder, scenarioID, root string) {
	sc, found := resolveRenderScenario(root, scenarioID)
	fmt.Fprintf(b, "  @%s\n", scenarioID)
	if !found {
		fmt.Fprintf(b, "  Scenario: %s\n", scenarioID)
		fmt.Fprintf(b, "    # Scenario %s does not resolve under spec/scenarios/ or .agents/holdout/.\n", scenarioID)
		return
	}
	title := sc.Goal
	if strings.TrimSpace(title) == "" {
		title = scenarioID
	}
	fmt.Fprintf(b, "  Scenario: %s\n", title)
	renderScenarioSteps(b, sc)
}

// renderScenarioSteps writes Gherkin Given/When/Then steps for a scenario.
// When the scenario declares no structured steps it falls back to a single
// descriptive comment so the renderer never crashes or fabricates steps.
func renderScenarioSteps(b *strings.Builder, sc renderScenario) {
	if !hasStructuredSteps(sc) {
		b.WriteString("    # Scenario lacks structured given/when/then; no Gherkin steps to render.\n")
		if strings.TrimSpace(sc.Goal) != "" {
			fmt.Fprintf(b, "    # Goal: %s\n", sc.Goal)
		}
		return
	}
	writeStepGroup(b, "Given", sc.Given)
	writeStepGroup(b, "When", sc.When)
	writeStepGroup(b, "Then", sc.Then)
}

// hasStructuredSteps reports whether a scenario declares any structured step.
func hasStructuredSteps(sc renderScenario) bool {
	return len(sc.Given) > 0 || len(sc.When) > 0 || len(sc.Then) > 0
}

// writeStepGroup writes a keyword's steps, using the keyword for the first
// step and "And" for subsequent steps, per Gherkin convention.
func writeStepGroup(b *strings.Builder, keyword string, steps []string) {
	for i, step := range steps {
		kw := keyword
		if i > 0 {
			kw = "And"
		}
		fmt.Fprintf(b, "    %s %s\n", kw, strings.TrimSpace(step))
	}
}

// resolveRenderScenario reads a scenario JSON, checking the promoted spec
// location (spec/scenarios/<id>.json) before the ad hoc holdout location
// (.agents/holdout/<id>.json), per ADR-0003 resolution order.
func resolveRenderScenario(root, id string) (renderScenario, bool) {
	for _, rel := range [][]string{
		{"spec", "scenarios", id + ".json"},
		{".agents", "holdout", id + ".json"},
	} {
		path := filepath.Join(append([]string{root}, rel...)...)
		if sc, ok := readRenderScenario(path); ok {
			return sc, true
		}
	}
	return renderScenario{}, false
}

// readRenderScenario reads and decodes a scenario JSON file. The second return
// is false when the file is absent or malformed.
func readRenderScenario(path string) (renderScenario, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return renderScenario{}, false
	}
	var sc renderScenario
	if err := json.Unmarshal(data, &sc); err != nil {
		return renderScenario{}, false
	}
	return sc, true
}

func init() {
	goalsRenderCmd.Flags().StringVar(&goalsRenderOut, "out", "", "Write Gherkin to this file instead of stdout")
	goalsCmd.AddCommand(goalsRenderCmd)
}
