// practices: [agile-manifesto, dora-metrics]
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/boshu2/agentops/cli/internal/domainslice"
)

// scaffoldDomainNamePattern mirrors the domain-name constraint in
// schemas/domain-slice-manifest.v1.schema.json. A scaffold name that does not
// match would produce a manifest the schema/loader rejects, so it is checked
// before any file is written.
var scaffoldDomainNamePattern = regexp.MustCompile(`^[a-z][a-z0-9-]*$`)

// domainScaffoldTemplate is the body written for a new domain-slice manifest by
// the phased command scaffold-domain flag. The %[1]s is substituted with the
// domain name. It MUST validate against schemas/domain-slice-manifest.v1.schema.json
// and decode via domainslice.Load — see TestRPIPhasedScaffoldDomain_RoundTrips.
const domainScaffoldTemplate = `# Domain-slice manifest for the %[1]s domain.
# Generated by: ao rpi phased --scaffold-domain %[1]s
# Validates against schemas/domain-slice-manifest.v1.schema.json.
# See docs/adr/ADR-0004-domain-slice-manifest-contract.md.
#
# Edit the placeholder values below to describe your bounded context, then:
#   ao rpi phased --domain %[1]s "<goal>"   # run RPI scoped to this slice
#   ao goals scenarios --lint                # check executable-spec links
#   ao rpi phased --domain %[1]s --dry-run "<goal>"  # preview prompts

schema_version: 1

# Short machine-readable name — matches this directory under docs/domains/.
domain: %[1]s

# Semver for this manifest (not the implementation). Increment on structural changes.
version: 0.1.0

# One sentence: what this slice owns and explicitly does NOT own.
bounded_context: >
  TODO: describe what the %[1]s domain slice owns and what it does NOT own.

# Stable directive IDs from GOALS.md whose acceptance this slice owns.
# Pattern: d-<slug>. Replace with the real directive IDs for this slice.
directive_ids:
  - d-%[1]s-placeholder

# Promoted spec scenario IDs (spec/scenarios/) that constitute delivery.
# Leave empty until scenarios are promoted, or list real scenario IDs.
scenario_ids: []

# Repo-relative paths forming the primary implementation surface.
# At least one entry is required.
context_roots:
  - cli/

# Read-fence allow list (gitignore syntax). Agents may read matching files.
allowed_read_globs:
  - cli/**
  - docs/domains/%[1]s/**
  - GOALS.md

# Read-fence deny list. Denied globs take precedence over allowed_read_globs.
# Add globs for any implementation detail unrelated to this slice.
denied_read_globs:
  - "**/testdata/**"

# Ordered validation steps run after each implementation phase.
validation_commands:
  - label: build
    command: "cd cli && go build ./cmd/ao/..."
    working_dir: cli
    timeout_seconds: 60

# Team or person responsible for this domain slice.
owner: maintainers
`

// scaffoldDomainResult captures what scaffoldDomainManifest wrote, so callers
// (and tests) can inspect the outcome without re-reading the filesystem.
type scaffoldDomainResult struct {
	Domain       string
	ManifestPath string // repo-relative
	Created      bool   // true when a new file was written
	Overwritten  bool   // true when an existing file was replaced (--force)
}

// validateScaffoldDomainName rejects domain names that would not match the
// schema's domain pattern, before any file is written.
func validateScaffoldDomainName(name string) error {
	name = strings.TrimSpace(name)
	if name == "" {
		return fmt.Errorf("--scaffold-domain requires a non-empty domain name")
	}
	if !scaffoldDomainNamePattern.MatchString(name) {
		return fmt.Errorf("invalid domain name %q: must match ^[a-z][a-z0-9-]*$", name)
	}
	return nil
}

// scaffoldDomainManifest writes a domain-slice manifest template at
// docs/domains/<name>/manifest.yaml under cwd. An existing manifest is left
// untouched unless force is set. The written template is validated through
// domainslice.Load so a scaffold never produces an invalid manifest.
func scaffoldDomainManifest(cwd, name string, force bool) (*scaffoldDomainResult, error) {
	if err := validateScaffoldDomainName(name); err != nil {
		return nil, err
	}
	rel := domainManifestPath(name)
	abs := filepath.Join(cwd, rel)

	overwritten := false
	if _, err := os.Stat(abs); err == nil {
		if !force {
			return nil, fmt.Errorf(
				"domain manifest already exists at %s\nre-run with --force to overwrite it", rel)
		}
		overwritten = true
	}

	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		return nil, fmt.Errorf("create domain directory: %w", err)
	}
	body := fmt.Sprintf(domainScaffoldTemplate, name)
	if err := os.WriteFile(abs, []byte(body), 0o644); err != nil {
		return nil, fmt.Errorf("write domain manifest: %w", err)
	}
	if _, err := domainslice.Load(abs); err != nil {
		return nil, fmt.Errorf("scaffolded manifest failed validation: %w", err)
	}
	return &scaffoldDomainResult{
		Domain: name, ManifestPath: rel, Created: !overwritten, Overwritten: overwritten,
	}, nil
}

// runScaffoldDomain is invoked by the phased command when --scaffold-domain is
// set. It writes the manifest template, prints the next commands, and returns
// without starting an RPI run.
func runScaffoldDomain(cwd, name string, force bool) error {
	result, err := scaffoldDomainManifest(cwd, name, force)
	if err != nil {
		return err
	}
	printScaffoldDomainSummary(result)
	return nil
}

// printScaffoldDomainSummary prints what was scaffolded and names the next
// commands the operator should run.
func printScaffoldDomainSummary(r *scaffoldDomainResult) {
	verb := "Created"
	if r.Overwritten {
		verb = "Overwrote"
	}
	fmt.Printf("%s domain-slice manifest: %s\n", verb, r.ManifestPath)
	fmt.Println("Edit the placeholder bounded_context, directive_ids, and context_roots, then:")
	fmt.Printf("  ao rpi phased --domain %s \"<goal>\"            # run RPI scoped to this slice\n", r.Domain)
	fmt.Printf("  ao rpi phased --domain %s --dry-run \"<goal>\"   # preview the scoped prompts\n", r.Domain)
	fmt.Println("  ao goals scenarios --lint                       # lint executable-spec links")
}
